[package]
name = "zygui"
version = "0.1.0"
edition = "2024"

[dependencies]
gio = "0.20.11"
glib = "0.20.10"
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_18"] }
gtk4-macros = "0.9.5"
once_cell = "1.21.3"
